In [1]:
import numpy as np
# Fibonaci

def fib(n):
    v=[0,1]
    for i in range(n):
        v.append(sum(v[-2:]))
    return v

In [4]:
fib(5)

[0, 1, 1, 2, 3, 5, 8]

In [5]:
# zip
numberlist=[1,2,3,4,5]
letterlist=['A','B','C','D','E']
for num, lett in zip(numberlist,letterlist):
    print(num, lett)

1 A
2 B
3 C
4 D
5 E


In [6]:
for idx, (num, lett) in enumerate(zip(numberlist,letterlist)):
    print(idx, num, lett)

0 1 A
1 2 B
2 3 C
3 4 D
4 5 E


In [8]:
# generating random number
np.random.randn(2,5)

array([[-0.65531764, -0.00169316, -0.23783716, -1.09493436, -0.99765234],
       [-0.46871641,  1.50364064, -0.04090256,  0.88679075, -0.16014878]])

In [9]:
np.random.uniform(0,1,(2,5))


array([[0.18196794, 0.97751002, 0.53683337, 0.43990386, 0.57178162],
       [0.8818115 , 0.2333335 , 0.32200241, 0.71878548, 0.78462086]])

In [11]:
np.random.randint(0,5,(2,5))

array([[0, 3, 0, 0, 4],
       [1, 2, 2, 4, 1]], dtype=int32)

In [13]:
np.linspace(-4,13,85)

array([-4.        , -3.79761905, -3.5952381 , -3.39285714, -3.19047619,
       -2.98809524, -2.78571429, -2.58333333, -2.38095238, -2.17857143,
       -1.97619048, -1.77380952, -1.57142857, -1.36904762, -1.16666667,
       -0.96428571, -0.76190476, -0.55952381, -0.35714286, -0.1547619 ,
        0.04761905,  0.25      ,  0.45238095,  0.6547619 ,  0.85714286,
        1.05952381,  1.26190476,  1.46428571,  1.66666667,  1.86904762,
        2.07142857,  2.27380952,  2.47619048,  2.67857143,  2.88095238,
        3.08333333,  3.28571429,  3.48809524,  3.69047619,  3.89285714,
        4.0952381 ,  4.29761905,  4.5       ,  4.70238095,  4.9047619 ,
        5.10714286,  5.30952381,  5.51190476,  5.71428571,  5.91666667,
        6.11904762,  6.32142857,  6.52380952,  6.72619048,  6.92857143,
        7.13095238,  7.33333333,  7.53571429,  7.73809524,  7.94047619,
        8.14285714,  8.3452381 ,  8.54761905,  8.75      ,  8.95238095,
        9.1547619 ,  9.35714286,  9.55952381,  9.76190476,  9.96

In [17]:
ln = np.linspace(-4,13,85)
np.random.choice(ln, 3)

array([ 6.72619048, -2.17857143,  8.54761905])

In [19]:
# soft coding
numberlist=np.linspace(-4,13,8)
for idx in range(len(numberlist)):
    value=numberlist[idx]
    print(f"Iteration: {idx}, value: {value}")

Iteration: 0, value: -4.0
Iteration: 1, value: -1.5714285714285716
Iteration: 2, value: 0.8571428571428568
Iteration: 3, value: 3.2857142857142847
Iteration: 4, value: 5.7142857142857135
Iteration: 5, value: 8.142857142857142
Iteration: 6, value: 10.57142857142857
Iteration: 7, value: 13.0


In [25]:
# list comprehension
result=[]
for i in range(10):
    result.append(i**2)
result

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [26]:
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [27]:
# lambda function
def littlefun(x):
    return x**2-1
littlefun(5)

24

In [28]:
littlefun2 = lambda x: x**2-1
littlefun2(5)

24