In [16]:
import torch as tch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sympy.physics.control.control_plots import matplotlib

print(torch.__version__)

2.9.1+cpu


In [17]:
dir(tch)

['AVG',
 'AcceleratorError',
 'AggregationType',
 'AliasDb',
 'AnyType',
 'Argument',
 'ArgumentSpec',
 'AwaitType',
 'BFloat16Storage',
 'BFloat16Tensor',
 'BenchmarkConfig',
 'BenchmarkExecutionStats',
 'Block',
 'BoolStorage',
 'BoolTensor',
 'BoolType',
 'BufferDict',
 'ByteStorage',
 'ByteTensor',
 'CallStack',
 'Capsule',
 'CharStorage',
 'CharTensor',
 'ClassType',
 'Code',
 'CompilationUnit',
 'CompleteArgumentSpec',
 'ComplexDoubleStorage',
 'ComplexFloatStorage',
 'ComplexType',
 'ConcreteModuleType',
 'ConcreteModuleTypeBuilder',
 'DeepCopyMemoTable',
 'DeserializationStorageContext',
 'DeviceObjType',
 'DictType',
 'DisableTorchFunction',
 'DisableTorchFunctionSubclass',
 'DispatchKey',
 'DispatchKeySet',
 'DoubleStorage',
 'DoubleTensor',
 'EnumType',
 'ErrorReport',
 'Event',
 'ExcludeDispatchKeyGuard',
 'ExecutionPlan',
 'FatalError',
 'FileCheck',
 'FloatStorage',
 'FloatTensor',
 'FloatType',
 'FunctionSchema',
 'Future',
 'FutureType',
 'Generator',
 'GradScaler',
 'G

In [19]:
#scalar
scalar=tch.tensor(7)
scalar

tensor(7)

In [20]:
scalar.ndim

0

In [21]:
scalar.shape

torch.Size([])

In [22]:
scalar.item()

7

In [23]:
scalar.amax()

tensor(7)

# A vector is a single dimension tensor but can contain many numbers.

In [25]:
#vector
vector=tch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [26]:
vector.shape

torch.Size([5])

In [30]:
vector.item

<function Tensor.item>

In [29]:
vector.ndim

1

In [31]:
vector.amax()

tensor(5)

# Matrix
Wow! More numbers! Matrices are as flexible as vectors, except they've got an extra dimension.

In [34]:
matrix=tch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [35]:
matrix.shape

torch.Size([2, 2])

In [36]:
matrix.sum()

tensor(34)

In [37]:
matrix[0,0]

tensor(7)

In [38]:
matrix[0,1]

tensor(8)

In [39]:
matrix.ndim

2

In [40]:
matrix.amax()

tensor(10)

In [41]:
matrix.amin()

tensor(7)

In [42]:
matrix.absolute()

tensor([[ 7,  8],
        [ 9, 10]])

# Tensor

In [43]:
tensor=tch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
tensor.shape

torch.Size([3, 3])

In [45]:
tensor.sum()

tensor(45)

In [46]:
tensor.amin()

tensor(1)

In [47]:
tensor.absolute()

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
tensor.ndim

2

In [49]:
tensor.amax()

tensor(9)

In [50]:
tensor[0,0]
tensor[0,1]
tensor[0,2]

tensor(3)

In [52]:
tensor[1,2]

tensor(6)

In [57]:
tensor.item()

RuntimeError: a Tensor with 9 elements cannot be converted to Scalar

In [58]:
# 3 channel tensor
tensor2=tch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor2.shape

torch.Size([1, 3, 3])

# Random number

In [64]:
random_tensor=tch.rand(3,5,5)
random_tensor

tensor([[[0.1053, 0.9072, 0.5527, 0.3490, 0.3456],
         [0.9666, 0.8221, 0.2712, 0.6191, 0.7362],
         [0.9719, 0.0958, 0.6266, 0.7465, 0.7426],
         [0.5324, 0.8139, 0.5761, 0.3735, 0.0995],
         [0.6804, 0.1878, 0.2818, 0.5314, 0.8751]],

        [[0.7412, 0.4605, 0.9393, 0.7493, 0.5956],
         [0.5748, 0.3399, 0.8731, 0.8390, 0.6840],
         [0.0875, 0.6526, 0.9287, 0.9409, 0.3320],
         [0.6947, 0.6789, 0.0848, 0.3905, 0.1060],
         [0.6186, 0.6799, 0.9502, 0.8973, 0.0217]],

        [[0.6441, 0.0881, 0.3461, 0.0527, 0.4565],
         [0.4198, 0.3247, 0.3391, 0.5725, 0.6276],
         [0.2824, 0.0848, 0.6957, 0.8647, 0.4692],
         [0.0695, 0.2601, 0.6496, 0.2461, 0.7591],
         [0.4163, 0.4686, 0.6500, 0.2078, 0.4976]]])

In [65]:
random_tensor.shape

torch.Size([3, 5, 5])

In [75]:
#randint(low, high, size)
tch.randint(2,7,(3,5,5))

tensor([[[2, 4, 2, 2, 5],
         [4, 3, 2, 4, 6],
         [5, 4, 2, 2, 6],
         [3, 2, 2, 5, 6],
         [5, 4, 4, 5, 6]],

        [[4, 2, 3, 6, 2],
         [3, 5, 4, 3, 4],
         [4, 4, 3, 2, 3],
         [2, 4, 4, 4, 5],
         [5, 5, 5, 6, 2]],

        [[3, 2, 2, 2, 3],
         [4, 4, 3, 6, 3],
         [6, 4, 6, 5, 2],
         [3, 3, 5, 6, 5],
         [4, 4, 6, 4, 5]]])

In [76]:
tch.randn(3,5,5)

tensor([[[ 1.2082, -1.6093, -0.9867, -0.5602,  0.7826],
         [ 0.1674, -0.1117,  0.8620,  0.6730, -0.2833],
         [-0.6090, -1.3470, -0.0105,  2.5031,  1.8107],
         [ 1.7990,  0.9447, -1.3180, -0.5285, -0.7090],
         [-0.5988, -0.0428,  0.1993, -0.4472, -1.1545]],

        [[-0.3896, -0.6912, -1.2685,  0.9948, -1.1062],
         [ 1.0670,  0.7520, -0.9001,  1.9976,  0.6759],
         [ 2.4908, -1.3747,  0.5476,  0.5299, -0.3873],
         [-0.1016, -0.5079, -0.6040,  0.6078,  0.1729],
         [ 0.7038,  0.9609,  0.1069,  0.2829, -0.8533]],

        [[ 1.5446,  0.2429,  0.9389,  1.3875, -0.9383],
         [-2.2844,  0.8955, -0.7443,  1.5300, -1.4371],
         [ 1.3416,  0.8637,  0.1050,  0.1785, -0.1183],
         [ 1.5062, -0.6840,  0.1773,  0.0384, -0.1491],
         [-1.6140, -0.3158, -2.0751, -1.5580, -1.8196]]])

# Zeros and ones

In [78]:
zeros=tch.zeros(3,5,5)
zeros, zeros.dtype

(tensor([[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]),
 torch.float32)

In [79]:
# ones
ones=tch.ones(3,5,5)
ones, ones.dtype

(tensor([[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]),
 torch.float32)

# Creating a range and tensors like
Sometimes we might want a range of numbers, such as 1 to 10 or 0 to 100.

We can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1)
Note: In Python, we can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future

In [80]:
range_tensor=tch.range(3,5,5)

C:\Users\mdsan\AppData\Local\Temp\ipykernel_32380\46552583.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor=tch.range(3,5,5)


In [83]:
range_tensor=tch.arange(3,5,5)
range_tensor.size

<function Tensor.size>

In [84]:
range_tensor.ndim

1

In [85]:
range_tensor.amax()

tensor(3)

In [87]:
# ten_zeros=tch.zeros_like(input=zero_to_ten)
range_tensor

tensor([3])

# Getting information from Tensor

In [88]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2936, 0.9242, 0.5742, 0.0849],
        [0.7574, 0.8216, 0.4780, 0.8166],
        [0.6397, 0.2618, 0.7529, 0.9064]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# tensor operations
- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [94]:
tensor=tch.tensor(tch.arange(1,10,1))
tensor

C:\Users\mdsan\AppData\Local\Temp\ipykernel_32380\2478489523.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor=tch.tensor(tch.arange(1,10,1))


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
tensor+10

tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [96]:
tensor-10

tensor([-9, -8, -7, -6, -5, -4, -3, -2, -1])

In [97]:
tensor*10

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Multiplication

In [99]:
tch.tensor([1, 2, 3]) * tch.tensor([1,2,3])

tensor([1, 4, 9])

The inner dimensions must match:

-(3, 2) @ (3, 2) won't work
-(2, 3) @ (3, 2) will work
-(3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:

-(2, 3) @ (3, 2) -> (2, 2)
-(3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

# Common error in deep learning is shape error

In [102]:
# Shapes need to be in the right way
tensor_A = tch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=tch.float32)

tensor_B = tch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=tch.float32)

tch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

- torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
- tensor.T - where tensor is the desired tensor to transpose.

In [103]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [104]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [105]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [106]:
tensor_A*tensor_B

tensor([[ 7., 20.],
        [24., 44.],
        [45., 72.]])

Reshaping, stacking, squeezing and unsqueezing
- Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

- reshape # Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
- view # Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
- stack #Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
- squeeze #Squeezes input to remove all the dimenions with value 1.
- unsqueeze #Returns input with a dimension value of 1 added at dim.
- permute #Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [108]:
x=tch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [119]:
# Now let's add an extra dimension with torch.reshape().
x_reshaped=x.reshape(1,-1)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [120]:
# Change view (keeps same data as original but changes view)
z=x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [121]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [122]:
z[:,0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

- Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

- So changing the view changes the original tensor too.

# Stack

In [127]:
x_stacked=tch.stack([x,x,x,x],dim=-1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]),
 torch.Size([7, 4]))

# squeeze
- How about removing all single dimensions from a tensor?

- To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1).

In [131]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [133]:
y=x_stacked.flatten()
y, y.shape

(tensor([5., 5., 5., 5., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4., 5., 5.,
         5., 5., 6., 6., 6., 6., 7., 7., 7., 7.]),
 torch.Size([28]))

# unsqueeze

In [134]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


# permute

In [135]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
